apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend-deployment
  labels:
    app: api-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-backend
  template:
    metadata:
      labels:
        app: api-backend
    spec:
      containers:
      - name: api-backend-container
        image: lugar2020/springboot-backend:docker_tag
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8020

---

apiVersion: v1
kind: Service
metadata:
  name: api-backend-service
  labels:
    name: api-backend-service
spec:
  ports:
    - port: 8020
      targetPort: 8020
  selector:
    app: api-backend