apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-database-deployment
  labels:
    app: mysql-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-database
  template:
    metadata:
      labels:
        app: mysql-database
    spec:
      containers:
      - name: mysql-database-container
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: kemane
        - name: MYSQL_DATABASE
          value: crud

---

apiVersion: v1
kind: Service
metadata: 
  name: mysql-database-service
  labels:
    name: mysql-database-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql-database