apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-deployment
  labels:
    app: react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend-container
        image: lugar2020/react-frontend:docker_tag
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata: 
  name: react-frontend-service
  labels:
    name: react-frontend-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30006
  selector:
    app: react-frontend